### ISSUE TITLE
builder.load(slidePath) not working...

### ISSUE THREAD

**Issue by razorsyntax** [sajjaphani/nativescript-carousel-ng#1]
In` welcome.component.ts` in the line with `slides.push(builder.load(slidePath))`, 

I'm getting the error:
`Error: Failed to load component from module: undefined.xml or file: /data/data/{{obfuscated}}/files/app/pages/welcome/slides/slide1.xml`

I can validate that the path is valid and the folder structure is valid.

One possible issue is that the file-system isn't seeing that folder... but that doesn't make sense.

I'm using the file-system elsewhere to validate that files exist for images.  But when I use it to validate that the pages folder exists, it always fails.

Is there any way to force Nativescript or the file-system to see the folder?  I can't find anywhere on the site, Stackoverflow, or etc to resolve this issue.  Any help is appreciated.

**Comment by darkmantle** [comment]
Did you solve this? Because I'm getting the exact same error now.

**Comment by wibimaster** [comment]
Because the file doesn't exist : 

      const currentAppFolder = knownFolders.currentApp();
      currentAppFolder.getEntities().then(data => {
        data.forEach(d => {
          console.log(d.path);
        })
      })

I'm also looking for another way to do it..

**Comment by sajjaphani** [comment]
Can you please provide more details of the issues observed? 

This has been developed using NativeScript version 5.x. There has been a lot of changes to the framework, and I think it starts breaking from version 6.
